# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\x12\x05hello\")\n\x0cHelloMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"!\n\x0cReplyMessage\x12\x11\n\treply_msg\x18\x01 \x01(\t2N\n\rHelloService\x12=\n\x0bHelloServer\x12\x13.hello.HelloMessage\x1a\x13.hello.ReplyMessage\"\x00(\x01\x30\x01\x62\x06proto3'
)




_HELLOMESSAGE = _descriptor.Descriptor(
  name='HelloMessage',
  full_name='hello.HelloMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello.HelloMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='hello.HelloMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=63,
)


_REPLYMESSAGE = _descriptor.Descriptor(
  name='ReplyMessage',
  full_name='hello.ReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_msg', full_name='hello.ReplyMessage.reply_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['HelloMessage'] = _HELLOMESSAGE
DESCRIPTOR.message_types_by_name['ReplyMessage'] = _REPLYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloMessage = _reflection.GeneratedProtocolMessageType('HelloMessage', (_message.Message,), {
  'DESCRIPTOR' : _HELLOMESSAGE,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloMessage)
  })
_sym_db.RegisterMessage(HelloMessage)

ReplyMessage = _reflection.GeneratedProtocolMessageType('ReplyMessage', (_message.Message,), {
  'DESCRIPTOR' : _REPLYMESSAGE,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.ReplyMessage)
  })
_sym_db.RegisterMessage(ReplyMessage)



_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='hello.HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloServer',
    full_name='hello.HelloService.HelloServer',
    index=0,
    containing_service=None,
    input_type=_HELLOMESSAGE,
    output_type=_REPLYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _SAMPLESERVICE

# @@protoc_insertion_point(module_scope)
